name: Retrain and Deploy Iris Model

on:
  push:
    paths:
      - 'data/Iris.csv'
      - 'src/models.py'
      - 'src/main.py'

jobs:
  retrain_and_build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Retrain model
      - name: Train iris models
        run: |
          python src/main.py   # this must save best_model.pkl + label_encoder.pkl to src/

      # Login to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner,, }}/iris-api:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner,, }}/iris-api:latest
